name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
            
      - run: |
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
          git push --mirror git@gitlab.com:3n3a/m183.git
